# Generated by Django 4.2.2 on 2024-06-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_data_payment_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="date",
            new_name="payment_date",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("CASH", "Наличные"), ("TRANSFER", "Перевод")],
                max_length=50,
                verbose_name="Метод оплаты",
            ),
        ),
    ]
