# Generated by Django 4.2.2 on 2024-06-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_delete_payments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="title_course",
            field=models.ForeignKey(
                help_text="Введите название курса",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons",
                to="materials.course",
                verbose_name="Название курса",
            ),
        ),
    ]
