# Generated by Django 4.2.2 on 2024-06-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0009_alter_payment_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
